bindings:
  - address: "127.0.0.1"
    protocol: "udp"
    port: 53
upstreams:
  - name: google
    dsn: "udp://8.8.8.8:53"
    timeout: 1s
policy:
  reload_interval: 6h
  matchers:
    - name: "hosts"
      type: "remap"
      source: file:///etc/antizapret-go/hosts.txt
      format: plain
      subdomains: true
fake_cidr: "10.30.0.0/15"
cache:
  capacity: 20000
  ttl: 24h
  min_ttl: 1m
  max_ttl: 24h
firewall:
  backend: nft            # nft | iptables
  set: "ANTIZAPRET_SET"   # только для nft
  chain: "ANTIZAPRET_CHAIN"
  ttl: 5m
request_timeout: 2s
logging_severity: "debug"
state_path: "/var/lib/antizapret-go/state.db"